version: "3"
services:
  web:
    image: shivam6131/nodejs-app:latest
    container_name: nodejs-app-container
    environment:
      - NODE_ENV=development
      - PORT=${PORT}
      - TESTENV=${TESTENV}
    ports:
      - "${PORT}:${PORT}"
