version: "3"
services:
  web:
    image: shivam6131/nodejs-app:latest
    container_name: nodejs-app-container
    args:
      PORT: $$${{ secrets.PORT }}
      TESTENV: $$${{ secrets.TESTENV }}
    ports:
      - "$${{ secrets.PORT }}:$${{ secrets.PORT }}"
    environment:
      - NODE_ENV=development
      - PORT=$${{ secrets.PORT }}
      - TESTENV=$${{ secrets.TESTENV }}
