# version: '3'
# services:
#   web:
#     build:
#       context: .
#       #will be usid while building image (In Dockerfile)
#       args:
#         NODE_ENV: production
#         APP_PORT: 4000
#     ports:
#       - "4000:4000"
#     #will be used inside node application (using process.env)
#     environment:
#       - NODE_ENV=production
#       - PORT=4000
#       - testENV=someValue

version: "3"
services:
  web:
    image: shivam6131/nodejs-app:latest
    container_name: nodejs-app-container
    args:
      PORT: ${{ secrets.PORT }}
      TESTENV: ${{ secrets.TESTENV }}
    ports:
      - "${{ secrets.PORT }}:${{ secrets.PORT }}"
    environment:
      - NODE_ENV=development
      - PORT=${{ secrets.PORT }}
      - TESTENV=${{ secrets.TESTENV }}
