name: CICD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and tag Docker image
        run: |
          docker build -t shivam6131/nodejs-app:latest -t shivam6131/nodejs-app:${{ github.sha }} .

      - name: Push Docker images
        run: |
          docker push shivam6131/nodejs-app:latest
          docker push shivam6131/nodejs-app:${{ github.sha }}

      # Create the environment file with secrets
      - name: Create environment file
        run: |
          echo "NODE_ENV=development" > env-file
          echo "PORT=${{ secrets.PORT }}" >> env-file
          echo "TESTENV=${{ secrets.TESTENV }}" >> env-file

      # Copy the environment file to the server
      - name: Copy environment file to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "env-file"
          target: "~/dockerComposeFiles/"

      - name: Copy docker-compose-uat.yml to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "./docker-compose-uat.yml"
          target: "~/dockerComposeFiles/"
          recursive: false  # Ensure this is false to prevent directory copy

      - name: Execute remote ssh commands (login dockerhub , pull images, run container).
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            docker pull shivam6131/nodejs-app:${{ github.sha }}
            docker rm -f nodejs-app-container || true
            ls -la
            cd ~/dockerComposeFiles
            source ./env-file
            docker-compose -f docker-compose-uat.yml up -d