name: CICD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Verify Docker login
        run: docker info | grep Username

      - name: Build and tag Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/nodejs-app:latest -t ${{ secrets.DOCKER_USERNAME }}/nodejs-app:${{ github.sha }} .

      - name: Push Docker images
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/nodejs-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/nodejs-app:${{ github.sha }}

  file_transfer:
    runs-on: ubuntu-latest
    needs: build
    steps:
      # Create the environment file with secrets (mention all envs here to add it to .env file)
      - name: Create environment file
        run: |
          echo "NODE_ENV=development" > .env
          echo "PORT=${{ secrets.PORT }}" >> .env
          echo "TESTENV=${{ secrets.TESTENV }}" >> .env
          echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}" >> .env

      # Copy the environment file to the server
      - name: Copy environment file to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: ".env"
          target: "~/dockerComposeFiles/"

      - name: List files for debugging
        run: ls -al

      - name: Copy docker-compose-uat.yml to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "./docker-compose-uat.yml"
          target: "~/dockerComposeFiles/"

  deploy:
    runs-on: ubuntu-latest
    needs: file_transfer
    steps:
      - name: Execute remote ssh commands (login to server, pull docker images, execute docker compose)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            docker pull ${{ secrets.DOCKER_USERNAME }}/nodejs-app:latest
            docker rm -f nodejs-app-container || true
            cd ~/dockerComposeFiles
            set -a
            source ./.env
            docker-compose -f docker-compose-uat.yml up -d