name: CICD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and tag Docker image
        run: |
          docker build -t shivam6131/nodejs-app:latest -t shivam6131/nodejs-app:${{ github.sha }} .

      - name: Push Docker images
        run: |
          docker push shivam6131/nodejs-app:latest
          docker push shivam6131/nodejs-app:${{ github.sha }}

      - name: Copy docker-compose-uat.yml to EC2
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.SSH_HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "${{ secrets.EC2_SSH_KEY }}" > private_key
            chmod 600 private_key
            scp -o StrictHostKeyChecking=no -i private_key docker-compose-uat.yml ${{ secrets.USERNAME }}@${{ secrets.SSH_HOST_DNS }}:~/docker-compose-uat.yml
            rm private_key
      
      - name: Execute remote ssh commands (login dockerhub , pull images, run container).
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            docker pull shivam6131/nodejs-app:${{ github.sha }}
            docker rm -f nodejs-app-container || true
            ls -la
            docker-compose -f ~/docker-compose-uat.yml up -d