name: CICD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build docker name
        run: docker build -t shivam6131/nodejs-app .
      - name: Publish image to dockerhub.
        run: docker push shivam6131/nodejs-app:latest

  # deploy:
  #   needs: build
  #   runs-on: [aws-ec2-new]
  #   steps:
  #     - name: Pull images fro docker hub
  #       run: docker pull shivam6131/nodejs-app:latest
  #     - name: Delete old container
  #       run: docker rm -f nodejs-app-container
  #     - name: run docker container
  #       run: docker run -d -p 4000:4000 --name nodejs-app-container shivam6131/nodejs-app
  
  deploy:
    needs: build
    runs-on: [aws-ec2-new]
    steps:
      - name: Set up environment variables
        run: |
          echo "TESTENV=${{ secrets.TESTENV }}" >> .env
          echo "PORT=${{ secrets.PORT }}" >> .env
          cat .env
      - name: Pull images fro docker hub
        run: docker pull shivam6131/nodejs-app:latest
      - name: Delete old container
        run: docker rm -f nodejs-app-container
      - name: navigate to dockercompose directory.
        run: |
          cd ../
          ls -l
      - name: run docker container
        run: docker-compose up -d
